### ISSUE TITLE
FPS Issue

### ISSUE THREAD

**Issue by IMWurden** [IMXNOOBX/cs2-external-esp#80]
When i use cs2-external-esp.exe my fps drops from 220 to 150-160, pls fix it

**Comment by Lex-999** [comment]
Experiencing a very significant fps drop on one of my systems.

**Specs**
CPU: AMD Ryzen 9 7900X
GPU: AMD Radeon 7900XT
MEM: 32GB
[](https://vimeo.com/manage/videos/882977047)

**Comment by ifBars** [comment]
> Experiencing a very significant fps drop on one of my systems.
> 
> 
> 
> **Specs**
> 
> CPU: AMD Ryzen 9 7900X
> 
> GPU: AMD Radeon 7900XT
> 
> MEM: 32GB
> 
> [Display of FPS Drop](https://vimeo.com/manage/videos/882977047)

The only sort of fps drops I see are those slight stutters when using the ESP. Although I did not experience this at all. Can you possibly check task manager and see how much resources the cheat is using? I recently commented out a purposeful 1 millisecond pause, that makes the esp look smoother, but in term uses more resources. I use an i5-11900k 3060TI 32GB of ram, and it works perfectly for me.

**Comment by ifBars** [comment]
Just an idea I just thought of. Possibly moving each rendering of esp per player onto its own thread. Could increase performance since each player would have their own rendering thread per say.

**Comment by Lex-999** [comment]
> > Experiencing a very significant fps drop on one of my systems.
> > **Specs**
> > CPU: AMD Ryzen 9 7900X
> > GPU: AMD Radeon 7900XT
> > MEM: 32GB
> > [Display of FPS Drop](https://vimeo.com/manage/videos/882977047)
> 
> The only sort of fps drops I see in your video, are those slight stutters when using the ESP. Although I did not experience this on my system, at all. Can you possibly check task manager and see how much resources the cheat is using? I recently commented out a purposeful 1 millisecond pause, that makes the esp look smoother, but in term uses more resources. I use an i5-11900k 3060TI 32GB of ram, and it works perfectly for me.

If you notice in the video I posted, the fps counter is on the left side in red. The video show that I am getting around 200–400 fps, with fps_max at 400. When I have the esp loaded, I am getting a consistent 60 fps the majority of the time.

The other PC I have runs it perfectly fine, which is odd. My other PC specs are Ryzen 9 5900X, Radeon 6950XT, and 32GB of memory. 

My resources seem completely normal and fine.
![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/97224560/9a3f75aa-6304-4c1d-a7b3-0058403d236c)

**Comment by ifBars** [comment]
> > > Experiencing a very significant fps drop on one of my systems.
> 
> > > **Specs**
> 
> > > CPU: AMD Ryzen 9 7900X
> 
> > > GPU: AMD Radeon 7900XT
> 
> > > MEM: 32GB
> 
> > > [Display of FPS Drop](https://vimeo.com/manage/videos/882977047)
> 
> > 
> 
> > The only sort of fps drops I see in your video, are those slight stutters when using the ESP. Although I did not experience this on my system, at all. Can you possibly check task manager and see how much resources the cheat is using? I recently commented out a purposeful 1 millisecond pause, that makes the esp look smoother, but in term uses more resources. I use an i5-11900k 3060TI 32GB of ram, and it works perfectly for me.
> 
> 
> 
> If you notice in the video I posted, the fps counter is on the left side in red. The video shows that I am getting around 200–400 fps normally, with fps_max at 400. When I have the esp loaded, I am getting a consistent 60 fps the majority of the time. It feels unplayable when I have the ESP on.
> 
> 
> 
> The other PC I have runs it perfectly fine, which is odd. My other PC specs are Ryzen 9 5900X, Radeon 6950XT, and 32GB of memory. 
> 
> 
> 
> My resources seem completely normal and fine.
> 
> ![image](https://github.com/IMXNOOBX/cs2-external-esp/assets/97224560/9a3f75aa-6304-4c1d-a7b3-0058403d236c)
> 
> 

It's very odd, but yet intriguing, that the issue only arises on one system. I know I have heard of performance varying system to system. Could you possibly add me on discord and we could discuss this further? My discord is p.penguin

**Comment by IMWurden** [comment]
Those are my pc specs:

RTX 3070 ROG STRIX

Intel Core i7-12700KF

32 GB Ram



Are my FPS too much low for my PC specs?

**Comment by IMXNOOBX** [comment]
It should be fixed in the last update thanks to https://github.com/IMXNOOBX/cs2-external-esp/pull/77

**Comment by IMXNOOBX** [comment]
> Just an idea I just thought of. Possibly moving each rendering of esp per player onto its own thread. Could increase performance since each player would have their own rendering thread per say.

Well, tbh im not sure if that's a great idea. Having multiple threads just to render the esp would cause more cpu consumption than fps reduction. And i think the issue was solved by the #77 as i have experienced a great improvement after it

**Comment by ifBars** [comment]
> > Just an idea I just thought of. Possibly moving each rendering of esp per player onto its own thread. Could increase performance since each player would have their own rendering thread per say.
> 
> Well, tbh im not sure if that's a great idea. Having multiple threads just to render the esp would cause more cpu consumption than fps reduction. And i think the issue was solved by the #77 as i have experienced a great improvement after it

Unfortunately PR #77 will not fix the issue. I talked to the person more, and the version they were using already had PR #77 merged and they still experienced the lag. The weird part was that they only had the issue of lag on one pc, the esp worked fine on their other pc.

**Comment by Lex-999** [comment]
After experimenting more on both computers, it seems as if my fps drops quite a bit on both with the esp loaded. Both computers go from fps_max 400 down to around 60. The weird part is that my main pc is very choppy with the esp loaded, however the other pc I am using isn't choppy at all.

**Comment by IMXNOOBX** [comment]
> Unfortunately PR #77 will not fix the issue. I talked to the person more, and the version they were using already had PR #77 merged and they still experienced the lag. The weird part was that they only had the issue of lag on one pc, the esp worked fine on their other pc.

I have no idea, but it might caused by the overlay not been able to render more than 60fps. But if you are playing fine and works fine on some computer and some others doesnt. idk

**Comment by Lex-999** [comment]
Just another update. I reinstalled my whole computer from scratch and only installed AMD Adrenaline for my Graphics drivers, Steam, CSGO, Firefox, and Visual Studio, and I am still having the issue on this computer.

**Comment by IMWurden** [comment]
Same issue, 150 fps max with 3070 i7 12700kf 32 gb of ram

**Comment by ifBars** [comment]
This is random, and I am just throwing this out there, but... memory leak?
